name = "alisareactionbot"
main = "api/worker.js"
compatibility_date = "2026-02-22"
compatibility_flags = ["nodejs_compat"]

[vars]
BOT_TOKEN = "8658849738:AAFzvmhsJJLyEx82GtXNOwr06MqlKEbE08c"
BOT_USERNAME = "ProAutoReaction_bot"
EMOJI_LIST = "👍❤🔥🥰👏😁🎉🤩🙏👌🕊😍🐳❤‍🔥💯⚡🏆"
RANDOM_LEVEL = "0"
RESTRICTED_CHATS = ""
